Repository kuru-project/main-website-client, pull requests merged in 2020-03, with the labels that each got.

#56 Change localhost:8000 to localhost:3000 and NuxtJS to NextJS at README.md
  README.md
Labels: bug

#58 Create a Header and a Footer component and put it inside Next's main layout #45
  components/Footer.tsx
  components/Header.tsx
  pages/_app.tsx
  pages/index.tsx
Labels: enhancement

#62 Create 2 empty pages for Mission and Vision #60
  pages/mission.tsx
  pages/vision.tsx
Labels: enhancement, good first issue

#64 Add a JavaScript Style Guide on the README #35
  README.md
Labels: enhancement, good first issue

#65 Link Twitter/Facebook/Discord on the Footer and Header #48
  components/Footer.tsx
  components/Header.tsx
  components/SocialMedia.tsx
Labels: enhancement, good first issue

#66 Create an empty opensource page #63
  pages/opensource.tsx
Labels: enhancement, good first issue

#67 Create an empty page for team members #51
  pages/team.tsx
Labels: enhancement, good first issue

#68 Create a simple Navigation on the Header #49
  components/Footer.tsx
  components/Header.tsx
  components/Navigation.tsx
  pages/about.tsx
  pages/index.tsx
  pages/mission.tsx
  pages/opensource.tsx
  pages/rules/discord.tsx
  pages/team.tsx
  pages/vision.tsx
Labels: enhancement, good first issue

#69 Work on the front-end-checklist #53
  components/OpenGraphMeta.tsx
  components/TwitterMeta.tsx
  pages/_app.tsx
Labels: enhancement, good first issue

#70 Add Ant Design to the project #40
  package.json
  pages/_app.tsx
  yarn.lock
Labels: enhancement, good first issue

#82 Add a bot page #81
  components/Navigation.tsx
  pages/bot.tsx
  yarn.lock
Labels: good first issue

#84 Create a relative path to import paths #83
  components/Footer.tsx
  components/Header.tsx
  next.config.js
  package.json
  pages/_app.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#88 Install Tailwind #86
  package.json
  pages/_app.tsx
  postcss.config.js
  styles.css
  yarn.lock
Labels: enhancement

#91 Hotfix: Update Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/epic_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/small_issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#92 Install Font Awesome
  components/SocialMedia.tsx
  package.json
  yarn.lock
Labels: enhancement
